# Generated by Django 2.0.6 on 2018-07-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20180713_0138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='data',
        ),
    ]
